### ISSUE TITLE
Error navigating visits on consolidated request summary

### ISSUE THREAD

**Issue by chrisortman** [sparc-request/sparc-request#1091]
If from the dashboard you click on _View Consolidated Request_  and then try to navigate the visits using the arrows
 
![screen shot 2017-08-22 at 11 19 03 am](https://user-images.githubusercontent.com/2954/29575969-d1bd80a4-872b-11e7-8ad9-fab5fbcd4c15.png)

The js endpoint that is requested generates an error:

```
service_calendars/table.js?admin=false&arm_id=157&page=2&pages%5B153%5D=1&pages%5B157%5D=1&portal=true&service_request_id=3600&tab=calendar&scroll=false

An ActionView::Template::Error occurred in service_calendars#table:

 undefined method `protocol' for nil:NilClass
 app/views/dashboard/sub_service_requests/_header.html.haml:25:in `_app_views_dashboard_sub_service_requests__header_html_haml___2988499649532368833_65202600'
```

I believe this was broken by 5fb1cb90bb2c120fbf97531cec87ffc06c6116d4 because the addition of the header partial requires the `sub_service_request` instance var to be set, but it is not because the `initialize_service_request_filter` gets skipped by  the `portal` query string argument

https://github.com/sparc-request/sparc-request/blob/master/app/controllers/service_calendars_controller.rb#L39

**Comment by chrisortman** [comment]
I can fix this with some guidance. Should the service request be loaded now and the `unless` filter on the action removed? Or should the template be able to handle not having a `sub_service_request` or should the header template not be rendered in this situation?

**Comment by WenjunHe1027** [comment]
Hi Chris,

This PR is a fix for the bug you are seeing:  #1036 

It will be included in the v3.0.0a release.

Thank you,
Wenjun

**Comment by chrisortman** [comment]
I merged the commits from #1036 and it fixed the issue for us.
Thanks!
